### ISSUE TITLE
Still unable to working

### ISSUE THREAD

**Issue by Aelfric1219** [Nomatter96/GladiatorLosSA_Cata4.4#1]
I tried to test it on Battleground and EpicBattleground, but it didn't work

**Comment by Nomatter96** [comment]
Can you tell me your language client?

**Comment by Nomatter96** [comment]
Can you tell me your client's language?

**Comment by Aelfric1219** [comment]
english language
and on EU severs

**Comment by Nomatter96** [comment]
Need more information, because it's work on my client.
What about your audio settings in game? (Audio must be ON)
Can you see addon on Settings -> Add-ons ( If not, try rename Addon folder on GladiatorLosSA without suffix)

**Comment by Aelfric1219** [comment]
I would have liked to add some additional skills in lua
But before that, I went to BG to test whether it can be used. I know how to set it up, but it doesn't work.

I think I need some help if your client works

**Comment by Nomatter96** [comment]
Can you show me what you did in lua?

**Comment by Aelfric1219** [comment]
i add some skills in spelllist.lua
such as demonsoul

[79460] = "demonsoul",

**Comment by Nomatter96** [comment]
Like this?
![Screenshot 2024-04-22 184127](https://github.com/Nomatter96/GladiatorLosSA_Cata4.4/assets/11832370/12510959-c447-4d5c-8d76-6904b2d65cee)

**Comment by Aelfric1219** [comment]
yes i want to add 79460 and 79462 also demonsuldown，These two cannot appear at the same time
And in order to fix the option, I modified option.lua
in options.lua (same file as the "add the 2"-fix), change line 224 from GSA:OnOptionCreate() to GSA:OnEnable()

![image](https://github.com/Nomatter96/GladiatorLosSA_Cata4.4/assets/156710196/dd214365-5af0-4a73-80ab-60bc4ed67923)


Finally, there is an error message

![image](https://github.com/Nomatter96/GladiatorLosSA_Cata4.4/assets/156710196/260b8700-e998-4b4d-ab98-5c233d4cd50b)

![image](https://github.com/Nomatter96/GladiatorLosSA_Cata4.4/assets/156710196/c51e6952-919d-4b01-86dd-c480ec33c88c)

**Comment by Nomatter96** [comment]
I get it. I don't why it work what it is, because not my code, but I solve this.
[79460] = "demonsoul",
[79462] = "demonsoul1",
demonsoul.ogg and demonsoul1.ogg copy and paste the same file.
Not good solution, but it's work
![Screenshot 2024-04-22 184127](https://github.com/Nomatter96/GladiatorLosSA_Cata4.4/assets/11832370/5beb62e7-ea6f-469b-9148-5e5a6d370f8e)

**Comment by Aelfric1219** [comment]
thank you very mush
and i found why i cant use it
cuz i fix this
in options.lua (same file as the "add the 2"-fix), change line 224 from GSA:OnOptionCreate() to GSA:OnEnable()

i change it back,its work,all good

**Comment by Nomatter96** [comment]
No problem!

**Comment by Nomatter96** [comment]
Btw i fix "Finally, there is an error message"
You can add "L["Racials"] = true " in Locals\enUS.lua, or download new last version
