### ISSUE TITLE
friendlyspell issue

### ISSUE THREAD

**Issue by Aelfric1219** [Nomatter96/GladiatorLosSA_Cata4.4#2]
I found out today while playing in the arena that it will voice announce some Spells from my teammates, such as Rogue's SAP and Cheep Shot
I don't know where to change it, it didn't appear in the previous WLK version
i was try to close friendlyinterrupted,but its not work

**Comment by Nomatter96** [comment]
I get it what's wrong with this. I haven't rogue teammate, can you try replace sap and cheep from auraApplied to castSuccess. It remove wrong sound alert of your teammate, but idk what about hostile rogue , need make some test.
P.S.
problem in handle logic of spells. It's work on wtlk version, because somebody made hardcode which handle logic error, but I don't like this method.

**Comment by Aelfric1219** [comment]
![image](https://github.com/Nomatter96/GladiatorLosSA_Cata4.4/assets/156710196/6b5c3368-ee5f-4851-abd3-797a75766cfe)

Do you mean to cancel this and then select SAP in buffApplied?

**Comment by Nomatter96** [comment]
yes

**Comment by Nomatter96** [comment]
but cheapShot only in BuffApplied. Open spelllist.lua and replace it to castSuccess

**Comment by Aelfric1219** [comment]
![image](https://github.com/Nomatter96/GladiatorLosSA_Cata4.4/assets/156710196/988acbb3-ef3f-4318-b8aa-d6bc7a5efe46)

Added
So should I uncheck all?

**Comment by Nomatter96** [comment]
its does not matter for your teammate now, his/her cheap or sap will not sound now, but i dont now about enemy rogue, try to check them and test plz, not necessary do it today :)

**Comment by Aelfric1219** [comment]
Okay, although I have finished the arena today, I will keep these tests. If there is any feedback, I will leave a message here

**Comment by kalevale1** [comment]
I'm trying to install the addon, but it doesn't show up in my addon list.

I have tried renaming the folder to GladiatorlosSA / GladiatorLosSA / GladiatorLosSA_Cata4.4 / GladiatorLosSA_Cata4.4-main But none of them seem to work :o

**Comment by Aelfric1219** [comment]
GladiatorLosSA2

**Comment by Aelfric1219** [comment]
I think I have discovered a new bug
Pala's HamJ also has a situation of mutual surveillance between us and the enemy, and I remember this situation existed during the WLK period
I tried using the same fix as rogue, but it didn't seem to work

**Comment by Nomatter96** [comment]
are you delete "[853] = "hammerOfJustice"," from auraApplied?

**Comment by Aelfric1219** [comment]
No, I just unchecked it. Do I need to delete it?

**Comment by Nomatter96** [comment]
yea, open spelllist.lua and delete plz, then feedback about is it work or not :)
I can test it only evening or tomorrow
By the way what about rogue? Is cheapShot sound from enemy?

**Comment by Aelfric1219** [comment]
HamJ's problem has been resolved
I previously unchecked check shot, but I think the same method should also solve this problem

However, the problem with SAP still exists, and GladiatorLosSA seems unable to notify rogue of SAP and Cheep Shot in the Stealth state

**Comment by Nomatter96** [comment]
> However, the problem with SAP still exists, and GladiatorLosSA seems unable to notify rogue of SAP and Cheep Shot in the Stealth state

Ok, I need to think how fix this ~14 years old problem :D
Try to fix the error this week

**Comment by Nomatter96** [comment]
> HamJ's problem has been resolved I previously unchecked check shot, but I think the same method should also solve this problem

It's work with cheap, because it is only in Aura Applied, but Ham exist in Aura Applied and Cast Success (Idk who did that mistake).
Need to refactor a lot of code to fix this and other logic troubles

**Comment by Nomatter96** [comment]
I complete fix problem with ability from invisible like cheap and make big code refactor.
Now I am testing and fix bugs. After this push new version

**Comment by Nomatter96** [comment]
Well. I'm push new version. If you find some new bug, make new issue please :)

Duplicate commit description:
fix bugs:
1. when spell isn't sound if it was used by enemy in invisible state
2. spell isn't shown if spell in spelllist.lua have the same file sound with another spell
3. trinket sound depends of Enabled Locations, but not only arena

refactor:
1. spelllist.lua
2. logic of play spell sound
3. delete useless duel mod
4. disable Ally Interrupt Alert (need remake it)

**Comment by Aelfric1219** [comment]
Do I need to keep my original spelllist.lua? Or can I use yours directly?
 I guess the new version you pushed doesn't include a demon soul?

**Comment by Nomatter96** [comment]
> Do I need to keep my original spelllist.lua? Or can I use yours directly? I guess the new version you pushed doesn't include a demon soul?

I added demonsoul, don't warry.
But you can't use old spelllist.lua.

**Comment by Nomatter96** [comment]
> Do I need to keep my original spelllist.lua? Or can I use yours directly? I guess the new version you pushed doesn't include a demon soul?

You can write me, what spell you want to add and I do it

**Comment by Aelfric1219** [comment]
Firstly, there is a lack of racial spell, followed by shadow sight, as well as the skull bash in the two forms of druids

For the time being, I have only thought of so much. If I find anything definite, I will leave you a message
Alternatively, you can teach me how to add spell ID

**Comment by Nomatter96** [comment]
> Firstly, there is a lack of racial spell, followed by shadow sight

ah, I forgot about racials and shadow sight. I'll fix it today.

> Alternatively, you can teach me how to add spell ID

You can open spelllist.lua and read my comments above. If you don't understand, then give me feedback what is unclear. I will rewrite.

I'm add skull bash (kick), a little bit later add another from bear form

**Comment by Nomatter96** [comment]
> Firstly, there is a lack of racial spell, followed by shadow sight

Done

**Comment by Aelfric1219** [comment]
Okay, I will test each project for any issues

**Comment by Nomatter96** [comment]
> Okay, I will test each project for any issues

Well, I've made a few more changes/fixes.
fix spell tooltips, which don't hide
fix when try use open configuration button first time after reload, but nothing happen then need close addon's option frame and open again (It was very annoying)

try use last version.

P.S.
I think soon to add this version addon in CurseForge, because it is already more better, then other and previous version of GladiatorlosSA. Don't know why someone didn't fix old bugs after ~15 years old addon

**Comment by Aelfric1219** [comment]
It's not arena time yet, but I think I found two voice file naming errors
The correct name should be：

priest
[8122]={soundName="fear4",

WARLOCK
[5484]={soundName="fear2",

WARRIOR
[5246]={soundName="fear3",

HUNTER
[90337] = { soundName = "？",         -- voice miss    
[19577] = { soundName = "intimidation",

**Comment by Nomatter96** [comment]
> It's not arena time yet, but I think I found two voice file naming errors The correct name should be：
> 
> priest [8122]={soundName="fear4",
> 
> WARLOCK [5484]={soundName="fear2",
> 
> WARRIOR [5246]={soundName="fear3",
> 
> HUNTER [90337] = { soundName = "？", -- voice miss [19577] = { soundName = "intimidation",

what's wrong with this?
in my spelllist I have this

[8122]  = { soundName = "fear",                  type = "cast"    },
[5484]  = { soundName = "howlOfTerror",          type = "cast"    },
[5246]  = { soundName = "fear",                  type = "cast"    },
[90337] = { soundName = "petStun",               type = "debuff"  },
[19577] = { soundName = "petStun",               type = "debuff"  },

and it's work

**Comment by Nomatter96** [comment]
may be you don't download last version?

**Comment by Aelfric1219** [comment]
I think this may be due to differences in language habits. We will distinguish between different names for "fear" from "warrior", "priority", and "warlock"

nvm

**Comment by Nomatter96** [comment]
I understand. I thought, that its fine, when spells are a kind of fear have one sound and etc.

**Comment by Aelfric1219** [comment]
> I understand. I thought, that its fine, when spells are a kind of fear have one sound and etc.

Haha, I understand what you mean. When I play in the EU, it's really not a problem. But as a Chinese language, these fears need to be expressed with more accurate words

But it's okay, I think someone will modify the spelllist in the Chinese environment

**Comment by Nomatter96** [comment]
ah. well :)
if you want you can change sound files. It's not complicate, if you don't know how, then I can tell you what to do. After that we can merge our versions in one addon :)
Unfortunately, I do not know Chinese for to do it myself

**Comment by Aelfric1219** [comment]
Discovered a new issue
There is no interrupt prompt in the new version, which was present in the old version

**Comment by Nomatter96** [comment]
> Discovered a new issue There is no interrupt prompt in the new version, which was present in the old version

Ok, check a little bit later. Weird issue

**Comment by Aelfric1219** [comment]
There is a great change. In the old version, when enemies used trinket, the voice prompt was only trinket, but now the prompt is class name trinket（such as priest trinket）, which is great

**Comment by Aelfric1219** [comment]
Additionally, the Shaman's Tremor Totem did not provide any prompts in actual combat
I'm sure I checked

**Comment by Aelfric1219** [comment]
There is no prompt for grounding totem either

**Comment by Nomatter96** [comment]
> There is no prompt for grounding totem either

fix every thing.
Open Abilities options and check again casts spells and abilities which you want to sound.
And add spirit link totem

**Comment by Nomatter96** [comment]
> There is no prompt for grounding totem either

Download new version :)

**Comment by Aelfric1219** [comment]
The voice of the totem is fine now

But there are still issues with the interrupted part, maybe I didn't describe it in detail enough.
In previous versions, if I interrupted the enemy, a voice message would appear saying "Interrupt success"

**Comment by Nomatter96** [comment]
> The voice of the totem is fine now
> 
> But there are still issues with the interrupted part, maybe I didn't describe it in detail enough. In previous versions, if I interrupted the enemy, a voice message would appear saying "Interrupt success"

Ok. I get it.
Interrupts is work, but not like you expected. When interrupt is success then sound of spell is play.
I am thinking about how to do it better
What you think about that?

**Comment by Nomatter96** [comment]
> But there are still issues with the interrupted part, maybe I didn't describe it in detail enough. In previous versions, if I interrupted the enemy, a voice message would appear saying "Interrupt success"

Download new version.
Now every kick is sounding even missed, but if kick is success, then after 0.5 sec delay will sound "Interrupt" sound

**Comment by Aelfric1219** [comment]
I tested the last version
In this version, you set the interrupt voice to "when the enemy successfully interrupts us, make a sound". I think this feature is good, and if it is used as a switchable option, it should also be used by some people.
But my previous feedback was that when I successfully interrupted the enemy, a voice prompt would appear. 
And in previous versions of the author, a sound appeared when the interruption was successful, but I couldn't find the name of the sound file. I hope it can help me because this is a annotation about the Chinese language. I should replace the sound file name that you are about to fix with this file
﻿
In addition, during testing, I often hear a voice call named "Success". I want to know which behavior of the other party triggered this sound, and I should replace it

**Comment by Nomatter96** [comment]
> I tested the last version In this version, ...

I understand you. Download new version
I add two different options and different sounds:
1. "Enemy Use Interrupt" which working like I sad before (sound file: interrupted.ogg)
2. "Friend use interrupt successful" which working when you or your party kick somebody successful (sound file: Lockout.ogg)

Check them in GladiatorlosSA->Abilities->General Options

**Comment by Nomatter96** [comment]
> In addition, during testing, I often hear a voice call named "Success". I want to know which behavior of the other party triggered this sound, and I should replace it

About this. Sound file is "success.ogg"
It's playing when some spells from "Spell Cast" and "Abilities / Cast Success" tabs is cast success (GladiatorlosSA->Abilities->Spell Cast and Abilities / Cast Success).
Important!
If spell is in "Spell Cast" and  "Abilities / Cast Success", then "Spell Cast" is responsible for sound spell by spell name and "Abilities / Cast Success" is responsible for sound "success.ogg"
If spell is only in "Abilities / Cast Success" then always sound spell by spell name

P.S. I know it is not simple to understand, but Blizzard's combat log is sucks for to handle logically

**Comment by Aelfric1219** [comment]
1. I just tested on the battlefield, and to my surprise, during the preparation phase, when both sides were not fully staffed, I didn't know the occupation information of the opposite side. However, GSA would tell me that the opposite side had used some skills in advance

But this problem still hasn't been solved for me. When the other party uses some skills, they still prompt "successful". I'm thinking about how to block this, will deleting the "successful" voice change? This setting was present in the old version, and I'm not sure if there is any connection between them
![image](https://github.com/Nomatter96/GladiatorLosSA_Cata4.4/assets/156710196/729d2394-b0a3-430d-9195-70ba85c36059)


2.I heard my teammate's interrupt voice, but I lacked my own interrupt voice for the enemy. When I interrupted the other person myself, there was no voice reminder, only a reminder from my teammates

**Comment by Nomatter96** [comment]
> 1. I just tested on the battlefield, and to my surprise, during the preparation phase, when both sides were not fully staffed, I didn't know the occupation information of the opposite side. However, GSA would tell me that the opposite side had used some skills in advance

I think this is not problem :)

> But this problem still hasn't been solved for me. When the other party uses some skills, they still prompt "successful".

It can't be. I was testing my own. Just disable this, like I said in my previous message 
![Screenshot 2024-06-16 094458](https://github.com/Nomatter96/GladiatorLosSA_Cata4.4/assets/11832370/63a50c6c-0309-4aa2-ab6a-380e8d59b9cf)

> I heard my teammate's interrupt voice, but I lacked my own interrupt voice for the enemy. When I interrupted the other person myself, there was no voice reminder, only a reminder from my teammates

I think this is not problem :)

**Comment by Nomatter96** [comment]
by the way I found issue with Freezing Trap and already fixed

**Comment by Aelfric1219** [comment]
> I think this is not problem :)

If I successfully interrupt the other person and I also want to add the sound of Lockout.ogg, what should I do?

**Comment by Aelfric1219** [comment]
> by the way I found issue with Freezing Trap and already fixed

I saw that you added Freezing Trap to the mage with a spell ID of 3355, but shouldn't this spell come from a hunter?

**Comment by Nomatter96** [comment]
> I saw that you added Freezing Trap to the mage with a spell ID of 3355, but shouldn't this spell come from a hunter?

Are you sure?
![Screenshot 2024-06-16 102522](https://github.com/Nomatter96/GladiatorLosSA_Cata4.4/assets/11832370/1779d5d3-c020-4a72-9205-096ff8f66282)

> If I successfully interrupt the other person and I also want to add the sound of Lockout.ogg, what should I do?

Well, I thought I got it. May be you are testing on units (not player). Now it's must working.
Download last revision

**Comment by Aelfric1219** [comment]
> Are you sure? 

oh,its my bad,i saw it wrong

>Well, I thought I got it. May be you are testing on units (not player). Now it's must working.
Download last revision

i test it on battleground，Only my teammates have prompts, and I myself have no prompts for the enemy's successful interruption

Should I go to the arena to test at night?

**Comment by Nomatter96** [comment]
> i test it on battleground，Only my teammates have prompts, and I myself have no prompts for the enemy's successful interruption

well, which class are you playing?

>Should I go to the arena to test at night?

ofc you can :) Battlegrounds are more stressful then arena for addon

**Comment by Aelfric1219** [comment]
> > i test it on battleground，Only my teammates have prompts, and I myself have no prompts for the enemy's successful interruption
> 
> well, which class are you playing?
> 
> > Should I go to the arena to test at night?
> 
> ofc you can :)


i play warlock,I tested Warlock, ret pala, Shaman kick。But just in Battleground, I can't hear the sound of my successful interruption

**Comment by Nomatter96** [comment]
I make last commit.
Try test on another classes. When you will kick, then event message will write on your chat. After that write which spells (spell name, spellID) not working

**Comment by Aelfric1219** [comment]
I have used the final version, which is very good and basically meets my expectations for this addon

The following feedback belongs to the "optimization" type and does not significantly affect usage, so the priority of modification is not as high

I will compare this with the one in Weakaura

![image](https://github.com/Nomatter96/GladiatorLosSA_Cata4.4/assets/156710196/ceee6f22-ea38-42f4-ba23-315be31ea127)

![image](https://github.com/Nomatter96/GladiatorLosSA_Cata4.4/assets/156710196/b4c8b04b-88a4-4b4b-8532-edb18ec60c05)

In the original version

world = no instance
But now, it seems that world=all

I think we can differentiate more carefully here

PS: I really enjoy hearing the prompt sound of successful interruption in raid

**Comment by Nomatter96** [comment]
It's good idea. I need to think about how to do it. But it's not so easily I think and I a little bit tired.
If you find out some critical bug, then I fix it immediately :)

**Comment by Nomatter96** [comment]
btw I make update of all sounds. Know addon size if 3.5 mb against ~23 mb. You can read commits :)

**Comment by Nomatter96** [comment]
Hey. I finally made release version and added addon on curse forge, if you want I can add your nickname (or something you want) like a good tester who helped me.

**Comment by Aelfric1219** [comment]
> Hey. I finally made release version and added addon on curse forge, if you want I can add your nickname (or something you want) like a good tester who helped me.

GZ!
I see that you have been fixing voice files lately, which is really great, and you have replaced OGG format voice with MP3. However, for Chinese voice users, most of the voice files of voice actors are in OGG format. I found the modification code in line 214 of (GladiatorlosSARemake. LUA)。I will make a note of this change to them

I am honored to be nominated by you. you can write my public nickname   妖梦跑哪去了(Aelfric)

P.S.  妖梦跑哪去了 is my Chinese nickname, with my English name in parentheses,it used to communicate with people who speak English

**Comment by Nomatter96** [comment]
>I see that you have been fixing voice files lately, which is really great, and you have replaced OGG format voice with MP3. However, for Chinese voice users, most of the voice files of voice actors are in OGG format. 

If it's matter then I can remove audio format in main code at all and add full audio name in spell list (like kick.mp3 or kick.ogg what ever you want to write in spelllist.lua, it will not matter). What you think about it? It's not complicate.

**Comment by Aelfric1219** [comment]
> > I see that you have been fixing voice files lately, which is really great, and you have replaced OGG format voice with MP3. However, for Chinese voice users, most of the voice files of voice actors are in OGG format.
> 
> If it's matter then I can remove audio format in main code at all and add full audio name in spell list (like kick.mp3 or kick.ogg what ever you want to write in spelllist.lua, it will not matter). What you think about it? It's not complicate.


I think this idea is great

OGG is not a good format, and older versions of audio in various languages can only be forced to use this format, making it impossible for people to modify older versions of audio files. Meanwhile, the new version of GSA also supports MP3 format, allowing players to DIY when facing special skills

**Comment by Nomatter96** [comment]
> I think this idea is great
> 
> OGG is not a good format, and older versions of audio in various languages can only be forced to use this format, making it impossible for people to modify older versions of audio files. Meanwhile, the new version of GSA also supports MP3 format, allowing players to DIY when facing special skills

Let's try new version :) With your name and removed binding of .mp3 file. Now you can write .ogg in spelllist.lua if you want

**Comment by Aelfric1219** [comment]
Can I add your Discord? I need to consult with you about the path issue of Chinese voice, but I cannot send it here

**Comment by Nomatter96** [comment]
> Can I add your Discord? I need to consult with you about the path issue of Chinese voice, but I cannot send it here

Discord: painwatcher
